<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">
<h2 style="color:#306998; font-size:23px; font-weight:700; border-bottom:1px solid #EAF2F8; padding-bottom:10px; margin:0 0 18px;">📖 انتخاب ردیف‌ها</h2>
<p style="margin:0 0 14px; text-align:justify;">در فصل قبل یاد گرفتیم چگونه <strong>ستون</strong> (خط عمودی جدول) انتخاب کنیم. حالا نوبت <strong>ردیف</strong> است: هر ردیف یک <strong>خط افقی</strong> است که اطلاعات <strong>یک خودرو</strong> را نگه می‌دارد — مدل، رنگ، قدرت، وزن و قیمت با هم.</p>
<div style="background:#F8F9FB; border-right:3px solid #4B8BBE; border-radius:6px; padding:12px 16px; margin:0 0 26px;">
    <div style="font-weight:700; color:#306998; margin-bottom:6px;">🧠 مدل ذهنی</div>
    <p style="margin:0; text-align:right;">در اکسل، <strong>ردیف ۳</strong> یعنی یک مشاهده کامل (یک خودرو). <strong>انتخاب ردیف</strong> یعنی برداشتن آن خط افقی از جدول. در پانداس این کار روی محور <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">axis=0</code> است (محور عمودی = ردیف‌ها). برچسب هر ردیف در <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.index</code> ذخیره می‌شود.</p>
  </div>
<div style="background:#EAF2F8; border-right:3px solid #4B8BBE; border-radius:6px; padding:12px 16px; margin:18px 0; text-align:right; font-weight:600; font-size:18px; color:#306998;">ستون سمت <strong>چپ</strong> جدول (اعداد ۰، ۱، ۲، …) برچسب ردیف است — نه یک ستون داده. این برچسب‌ها را با <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.index</code> می‌بینیم.</div>
<p style="margin:10px 0 4px; text-align:justify;">همان DataFrame خودروها را بسازید. <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.head(2)</code> را اجرا کنید. ردیفی که index آن <strong>۰</strong> است مربوط به کدام خودرو است؟ ردیف index=<strong>1</strong> چطور؟</p>
  <!-- کد را خودت بنویس -->
</div>

In [1]:
import pandas as pd
import numpy as np

In [2]:
cars_dictionary = {
    "model" :[ "Peykan", "BMW X6", "Peugeot 206", "Tiba", "Nissan Junior", "Peykan Vanet", "renault 5"],
    "Color" :["Red", "White", "Black", "White", "Blue", "Red", "Silver"],
    "HP" :[48, 335, 105, 87, 93, 80, 48],
    "Weight (KG)": [990, 2320, 1025, 1027, 1540, 960, 850],
    "price" :[33, 2400, 105, 120, 230, 68, 38]
}
df = pd.DataFrame(cars_dictionary)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


,model,Color,HP,Weight (KG),price
0,Peykan,Red,48,990,33
1,BMW X6,White,335,2320,2400
2,Peugeot 206,Black,105,1025,105
3,Tiba,White,87,1027,120
4,Nissan Junior,Blue,93,1540,230
5,Peykan Vanet,Red,80,960,68
6,renault 5,Silver,48,850,38


In [3]:
df.head(2)

,model,Color,HP,Weight (KG),price
0,Peykan,Red,48,990,33
1,BMW X6,White,335,2320,2400


<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">
<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">🏷️ df.index — برچسب سمت چپ هر ردیف</h3><p style="margin:0 0 12px; font-size:14px; color:#78828C;">Attribute؛ بدون پرانتز</p>
<p style="margin:0 0 14px; text-align:justify;">وقتی DataFrame را می‌سازید، پانداس به‌طور پیش‌فرض به هر ردیف عدد می‌دهد: ۰، ۱، ۲، …، ۶ (برای ۷ خودرو). این اعداد <strong>index</strong> نامیده می‌شوند — برچسب ردیف، نه داده.</p>
<p style="margin:0 0 14px; text-align:justify;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.index</code> همان Attribute است که این برچسب‌ها را نشان می‌دهد. خروجی معمولاً شبیه <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">RangeIndex(start=0, stop=7, step=1)</code> است: از ۰ شروع، تا ۷ (بدون ۷)، گام ۱.</p>
<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
    <thead><tr style="background:#EAF2F8;"><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">مفهوم</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">کد</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">معنی</th></tr></thead>
    <tbody><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;">برچسب ردیف‌ها</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.index</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;">لیست ۰، ۱، ۲، …</td></tr><tr style="background:#FAFBFC;"><td style="padding:10px 12px; border:1px solid #E6E9ED;">ردیف با index=0</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">—</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">اولین خودرو: Peykan</td></tr><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;">ردیف با index=1</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">—</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">دومین خودرو: BMW X6</td></tr><tr style="background:#FAFBFC;"><td style="padding:10px 12px; border:1px solid #E6E9ED;">ردیف با index=3</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">—</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">چهارمین خودرو: Tiba</td></tr></tbody>
  </table>
<p style="margin:0 0 14px; text-align:justify;">برای پیدا کردن خودروی ردیف ۳، به جدول <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df</code> نگاه کنید: ردیفی که در ستون چپ عدد <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">3</code> دارد، همان Tiba است.</p>
<p style="margin:10px 0 4px; text-align:justify;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.index</code> را چاپ کنید. سپس بدون کد اضافه، فقط با نگاه به <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df</code> بگویید ردیف با index برابر <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">4</code> کدام مدل خودرو است.</p>
  <!-- کد را خودت بنویس -->
</div>

In [4]:
df.index

RangeIndex(start=0, stop=7, step=1)

<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">
<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">🔄 set_index("model") — برچسب معنادار به‌جای ۰، ۱، ۲</h3><p style="margin:0 0 12px; font-size:14px; color:#78828C;">Method؛ با پرانتز</p>
<p style="margin:0 0 14px; text-align:justify;">گاهی عدد ۰ و ۱ برای برچسب ردیف راحت نیست — می‌خواهیم مستقیم بگوییم <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"Peykan"</code> یا <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"BMW X6"</code>. برای این کار یک ستون (مثلاً <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">model</code>) را به <strong>برچسب ردیف</strong> تبدیل می‌کنیم:</p>
<p style="margin:0 0 14px; text-align:justify;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.set_index("model")</code> — این یک <strong>Method</strong> است (با پرانتز). ستون <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">model</code> دیگر در جدول به‌صورت ستون داده دیده نمی‌شود؛ مقدار هر <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">model</code> (Peykan، BMW X6، …) جایگزین ۰، ۱، ۲ در سمت چپ می‌شود.</p>
<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
    <thead><tr style="background:#EAF2F8;"><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">وضعیت</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">سمت چپ جدول</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">ستون model</th></tr></thead>
    <tbody><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;">قبل از set_index</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">۰، ۱، ۲، …</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">ستون عادی با مقادیر Peykan، BMW X6، …</td></tr><tr style="background:#FAFBFC;"><td style="padding:10px 12px; border:1px solid #E6E9ED;">بعد از set_index</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">Peykan، BMW X6، …</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">دیگر ستون نیست — برچسب ردیف است</td></tr></tbody>
  </table>
<div style="background:#FFF8F0; border-right:3px solid #E6A23C; border-radius:6px; padding:12px 16px; margin:18px 0;">
    <div style="font-weight:700; color:#B7791F; margin-bottom:6px;">⚠️ اشتباه رایج</div>
    <p style="margin:0; text-align:right;">بعد از <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">set_index("model")</code>، <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"model"</code> دیگر در <strong>سرستون‌های</strong> جدول دیده نمی‌شود — چون به برچسب ردیف (سمت چپ) منتقل شده. (نام ستون‌ها را در فصل ۰۶ یاد گرفتید.)</p>
  </div>
<p style="margin:10px 0 4px; text-align:justify;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.set_index("model", inplace=True)</code> را اجرا کنید. <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.index</code> و <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.head(2)</code> را ببینید. اولین برچسب index چیست؟ چند ستون داده باقی مانده؟</p>
  <!-- کد را خودت بنویس -->
</div>

In [6]:
df.set_index("model", inplace=True)
df

,Color,HP,Weight (KG),price
model,,,,
Peykan,Red,48,990,33
BMW X6,White,335,2320,2400
Peugeot 206,Black,105,1025,105
Tiba,White,87,1027,120
Nissan Junior,Blue,93,1540,230
Peykan Vanet,Red,80,960,68
renault 5,Silver,48,850,38


<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">
<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">📊 وقتی یک ردیف انتخاب شود — خروجی چه شکلی است؟</h3><p style="margin:0 0 12px; font-size:14px; color:#78828C;">Series برای یک ردیف</p>
<p style="margin:0 0 14px; text-align:justify;">قبل از یادگیری <strong>کد</strong> انتخاب ردیف (در فصل‌های <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">loc</code> و <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code>)، باید بدانیم <strong>خروجی</strong> چه شکلی است:</p>
<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
    <thead><tr style="background:#EAF2F8;"><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">تعداد ردیف انتخاب‌شده</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">نوع خروجی</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">index خروجی</th></tr></thead>
    <tbody><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;">یک ردیف</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;">نام ستون‌های باقی‌مانده (Color، HP، price، …)</td></tr><tr style="background:#FAFBFC;"><td style="padding:10px 12px; border:1px solid #E6E9ED;">چند ردیف</td><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">DataFrame</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;">برچسب همان ردیف‌های انتخاب‌شده</td></tr></tbody>
  </table>
<p style="margin:0 0 14px; text-align:justify;">مثال (بعد از <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">set_index</code>): اگر ردیف <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"BMW X6"</code> را داشته باشیم، <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code>ی با پنج مقدار می‌گیریم — مثلاً Color=White، HP=335، Weight (KG)=2320، price=2400. index این <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code> نام ستون‌ها و مقدار آنهاست.</p>
<div style="background:#F8F9FB; border-right:3px solid #4B8BBE; border-radius:6px; padding:12px 16px; margin:0 0 26px;">
    <div style="font-weight:700; color:#306998; margin-bottom:6px;">🧠 مدل ذهنی</div>
    <p style="margin:0; text-align:right;">یک ردیف = یک <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code> افقی (پانداز به صورت عمودی نمایش میدهد). چند ردیف = <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">DataFrame</code> کوچک‌تر. این قرینه انتخاب ستون است: آنجا یک ستون → <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code>؛ اینجا یک ردیف → <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code>.</p>
  </div>
<p style="margin:10px 0 4px; text-align:justify;">بعد از <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">set_index</code>، به ردیف <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">"Tiba"</code> در جدول <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df</code> نگاه کنید. چند مقدار (ستون داده) دارد؟ نام آن ستون‌ها را از سرستون جدول بنویسید.</p>
  <!-- کد را خودت بنویس -->
</div>

In [ ]:
df

,Color,HP,Weight (KG),price
model,,,,
Peykan,Red,48,990,33
BMW X6,White,335,2320,2400
Peugeot 206,Black,105,1025,105
Tiba,White,87,1027,120
Nissan Junior,Blue,93,1540,230
Peykan Vanet,Red,80,960,68
renault 5,Silver,48,850,38


In [11]:
print(f"Columns: {df.columns.tolist()}")

Columns: ['Color', 'HP', 'Weight (KG)', 'price']


<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">

<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">⚖️ دو سؤال درباره‌ی یک ردیف: برچسب یا موقعیت؟</h3>
<p style="margin:0 0 12px; font-size:14px; color:#78828C;">پیش‌درآمدی بر loc و iloc</p>

<p style="margin:0 0 14px; text-align:justify;">برای رسیدن به یک ردیف در دیتافریم، همیشه یکی از این دو سؤال را می‌پرسیم: «این ردیف چه نامی دارد؟» یا «این ردیف در کدام موقعیت جدول قرار دارد؟» در فصل‌های بعد، دو ابزار جدا برای پاسخ به همین دو سؤال معرفی می‌شوند:</p>

<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
  <thead>
    <tr style="background:#EAF2F8;">
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">سؤال</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">آنچه از پیش می‌دانیم</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">ابزار</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">مثال</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">خودروی Tiba در کدام ردیف است؟</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">نام (برچسب) ردیف</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">loc</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc["Tiba"]</code></td>
    </tr>
    <tr style="background:#FAFBFC;">
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">ردیف اول جدول چیست؟</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">شماره (موقعیت) ردیف، از ۰</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.iloc[0]</code></td>
    </tr>
  </tbody>
</table>

<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">وقتی برچسب با موقعیت فرق می‌کند</h3>

<p style="margin:0 0 14px; text-align:justify;">پیش از اجرای <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">set_index</code>، اندیس دیتافریم به‌طور پیش‌فرض همان شماره‌ی موقعیت است — برای همین در این حالت <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">loc</code> و <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code> به یک نتیجه می‌رسند. اما با دستور <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.set_index("model")</code>، برچسبِ هر ردیف عوض می‌شود، در حالی‌که موقعیت فیزیکی‌اش — یعنی جایی که در جدول قرار دارد — دست‌نخورده باقی می‌ماند:</p>

<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
  <thead>
    <tr style="background:#EAF2F8;">
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">موقعیت (iloc)</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">برچسب پیش از set_index</th>
      <th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">برچسب پس از set_index("model")</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">0</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">0</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">Peykan</td>
    </tr>
    <tr style="background:#FAFBFC;">
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">1</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">1</code></td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED;">BMW X6</td>
    </tr>
    <tr>
      <td style="padding:10px 12px; border:1px solid #E6E9ED; color:#9AA5B1;">…</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED; color:#9AA5B1;">…</td>
      <td style="padding:10px 12px; border:1px solid #E6E9ED; color:#9AA5B1;">…</td>
    </tr>
  </tbody>
</table>

<p style="margin:0 0 4px; text-align:justify;">به بیان دیگر: <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc[0]</code> همچنان به همان ردیف فیزیکی اول اشاره دارد؛ فقط نامش عوض شده است.</p>

<div style="background:#FFF8F0; border-right:3px solid #E6A23C; border-radius:6px; padding:12px 16px; margin:18px 0;">
  <div style="font-weight:700; color:#B7791F; margin-bottom:6px;">⚠️ اشتباه رایج</div>
  <p style="margin:0; text-align:right;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc[0]</code> همیشه اولین ردیف فیزیکی جدول را برمی‌گرداند، صرف‌نظر از برچسب اندیس. در مقابل، <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">loc["Peykan"]</code> ردیفی را برمی‌گرداند که برچسبش دقیقاً Peykan باشد، صرف‌نظر از موقعیتش در جدول. تا وقتی اندیس پیش‌فرض (RangeIndex) دست‌نخورده بماند، این دو یکی هستند؛ اما به‌محض تغییر اندیس، ممکن است دیگر به یک ردیف اشاره نکنند. این تفاوت را در فصل‌های ۰۸ و ۰۹ با تمرین عملی می‌بینید.</p>
</div>

<div style="background:#F1F8F3; border-right:3px solid #4CAF50; border-radius:6px; padding:12px 16px; margin:18px 0;">
  <div style="font-weight:700; color:#2E7D32; margin-bottom:6px;">🧪 امتحان کنید</div>
  <p style="margin:0; text-align:right;">پس از <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.set_index("Car")</code>، با دستور <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.index.get_loc("Tiba")</code> موقعیت عددی Tiba را پیدا کنید. آیا با جایگاهی که در ذهن داشتید یکسان است؟</p>
</div>
<!-- سلول کد بعدی: نتیجه‌ی get_loc را اینجا امتحان کنید -->

</div>


In [12]:
df.index.get_loc("Tiba")

3

<div dir="rtl" style="font-family:'Vazirmatn','IRANSans',Tahoma,Arial,sans-serif; font-size:17px; line-height:1.9; color:#33404d; max-width:760px; margin:0 auto;">
<h3 style="color:#306998; font-size:18px; margin:28px 0 6px;">✅ جمع‌بندی فصل</h3><p style="margin:0 0 12px; font-size:14px; color:#78828C;">انتخاب ردیف — مبانی</p>
<table dir="rtl" style="width:100%; border-collapse:collapse; margin:0 0 16px; font-size:15px;">
    <thead><tr style="background:#EAF2F8;"><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">مفهوم</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">توضیح</th><th style="padding:10px 12px; text-align:right; color:#306998; border:1px solid #E6E9ED;">فصل بعد</th></tr></thead>
    <tbody><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.index</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;">برچسب سمت چپ هر ردیف (۰، ۱، ۲ یا نام)</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">—</td></tr><tr style="background:#FAFBFC;"><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">set_index</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;">تبدیل یک ستون به برچسب ردیف</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">—</td></tr><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;">یک ردیف → <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">Series</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;">خروجی یک ردیف</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">—</td></tr><tr style="background:#FAFBFC;"><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">loc</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;">انتخاب با <strong>نام</strong> برچسب</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">فصل ۰۸</td></tr><tr><td style="padding:10px 12px; border:1px solid #E6E9ED;"><code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">iloc</code></td><td style="padding:10px 12px; border:1px solid #E6E9ED;">انتخاب با <strong>شماره</strong> موقعیت</td><td style="padding:10px 12px; border:1px solid #E6E9ED;">فصل ۰۹</td></tr></tbody>
  </table>
<p style="margin:0 0 14px; text-align:justify;">فصل بعد: <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">loc</code> — یاد می‌گیرید دقیقاً چگونه با <strong>نام</strong> ردیف (و ستون) داده انتخاب کنید؛ مثلاً <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc["BMW X6"]</code> یا <code dir="ltr" style="unicode-bidi:isolate; background:#EFF3F7; color:#4B8BBE; padding:1px 6px; border-radius:4px; font-family:Consolas,'Fira Code',monospace; font-size:14px;">df.loc["BMW X6", "price"]</code>.</p>
</div>